### ISSUE TITLE
thread 'main' panicked at 'Missing 963': src/lib.rs:666

### ISSUE THREAD

**Issue by maltee1** [matrix-org/rust-synapse-compress-state#107]
I'm getting this when running synapse_compress_state:
```
[2022-10-24T11:23:40Z INFO  synapse_auto_compressor::manager] Running compressor on room !dlPhxKlwObeRkhUZCm:maltee.de with chunk size 500
[2022-10-24T11:23:40Z ERROR panic] thread 'main' panicked at 'Missing 963': src/lib.rs:666
```
I'm not sure if that's a bug in the auto compressor or my database has an issue

**Comment by maltee1** [comment]
found a solution here: https://github.com/matrix-org/rust-synapse-compress-state/issues/79

**Comment by schildbach** [comment]
This is a duplicate of https://github.com/matrix-org/rust-synapse-compress-state/issues/78.
