### ISSUE TITLE
thread 'main' panicked at 'Missing 135224': src/lib.rs:668

### ISSUE THREAD

**Issue by ZhenyaPav** [matrix-org/rust-synapse-compress-state#124]
I get the following output when running the program:
```
[2023-07-30T10:04:56Z INFO  synapse_auto_compressor] synapse_auto_compressor started
[2023-07-30T10:04:56Z INFO  synapse_auto_compressor::manager] Running compressor on room !EVgDRwwKpuXCmFNPHG:matrix.org with chunk size 500
[2023-07-30T10:04:56Z ERROR panic] thread 'main' panicked at 'Missing 135224': src/lib.rs:668
```

My server is on Debian 11.

**Comment by ZhenyaPav** [comment]
Seems to be the same issue as in #79
