### ISSUE TITLE
thread 'main' panicked at 'Missing 39318': src/lib.rs:668

### ISSUE THREAD

**Issue by whotwagner** [matrix-org/rust-synapse-compress-state#148]
When I execute 

`synapse_auto_compressor -p 'postgresql://<USER>r:<PASSWORD>@localhost/synapse' -c 500 -n 100`

the following error returns:

```
[2024-09-09T20:05:24Z INFO  synapse_auto_compressor] synapse_auto_compressor started
[2024-09-09T20:05:24Z INFO  synapse_auto_compressor::manager] Running compressor on room !Room:server.tld with chunk size 500
[2024-09-09T20:05:24Z ERROR panic] thread 'main' panicked at 'Missing 39318': src/lib.rs:668
```

(I replaced the room-id)

I am currently using synapse_auto_compressor 0.1.3

Does anybody have an idea how to fix that?

**Comment by devonh** [comment]
Would you be able to try again with `RUST_BACKTRACE=1` to help determine which callsite is causing the panic?

**Comment by whotwagner** [comment]
Just setting the environment variable does not change the output. I still get the same error. I tried:

```
export RUST_BACKTRACE=1
synapse_auto_compressor -p 'postgresql://<USER>r:<PASSWORD>@localhost/synapse' -c 500 -n 100
```

**Comment by dasJ** [comment]
Happened to me as well after removing a room. The first line mentions that room:
```
[2024-09-13T16:59:35Z DEBUG tokio_postgres::query] executing statement s11 with parameters: ["!xxx:xxx", 8352225, 8345258]
[2024-09-13T16:59:37Z DEBUG synapse_compress_state::database] Got initial state from database. Checking for any missing state groups...
[2024-09-13T16:59:37Z DEBUG tokio_postgres::prepare] preparing query s12:
            SELECT target.prev_state_group, source.prev_state_group, state.type, state.state_key, state.event_id
            FROM state_group_edges AS target
            LEFT JOIN state_group_edges AS source ON (target.prev_state_group = source.state_group)
            LEFT JOIN state_groups_state AS state ON (target.prev_state_group = state.state_group)
            WHERE target.prev_state_group = ANY($1)

[2024-09-13T16:59:37Z DEBUG tokio_postgres::query] executing statement s12 with parameters: [[8345394, 8345619, 8345729, 8346492, 8346672, 8347428, 8347641, 8347776, 8347850, 8348424, 8348586, 8348881, 8349185, 8349232, 8349257, 8349362, 8349921, 8349955, 8350116, 8350188, 8350438, 8350760, 8350793, 8350930, 8351038,
8351160, 8351351, 8351364, 8351377, 8351649, 8351737, 8351778, 8351826, 8352004, 8352160, 8352170, 8352182, 8352204]]
[2024-09-13T16:59:37Z ERROR panic] thread 'main' panicked at 'Missing 8345258': src/lib.rs:668
```

**Comment by kescherCode** [comment]
Duplicate of #78
